version: '3'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  web:
    restart: always
    env_file:
      - ./.env.dev
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - 80:8000
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - 8001:8001
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - keycloak_postgres
  keycloak_postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
