version: '3'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  web: &web
    restart: always
    env_file:
      - .envs/.env.local
    build:
      context: ./
      dockerfile: compose/Dockerfile.local
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py create_admin &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      -

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/local-realm.json
    volumes:
      - ./compose/keycloak/local-realm.json:/tmp/local-realm.json
    ports:
      - 8080:8080
    depends_on:
      - keycloak_postgres

  keycloak_postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  celeryworker:
    <<: *web
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: celery -A config.celery_app worker -l INFO

  flower:
    <<: *web
    ports:
      - "5555:5555"
    command: celery 
      -A config.celery_app \
      -b "${CELERY_BROKER_URL}" \
      flower \
      --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"

  redis:
    image: redis:6
