site_name: umbrella
site_description: umbrella
repo_url: https://github.com/shuryhin-oleksandr/umbrella
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/shuryhin-oleksandr">shuryhin-oleksandr</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
