version: '3.8'

services:
  web: &web
    build: ./
    command: bash -c "
        python wait_for_postgres.py &&
        ./manage.py migrate --noinput &&
        ./manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./:/code
    expose:
      - 8000
    env_file:
      - .envs/.env.prod
      - .envs/.env.prod.db
  nginx-proxy:
    container_name: nginx-proxy
    build: compose/nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .envs/.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  certs:
  html:
  vhost:
  acme:
