version: '3'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
  web:
    restart: always
    env_file:
      - ./.env.prod
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000 &&
               ./gunicorn umbrella.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      - postgres
  documentation:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - 8001:8001
