version: '3.8'

services:
  web: &web
    build: ./
    image: umbrella_staging_web
    container_name: umbrella_staging_web
    command: bash -c "
      python wait_for_postgres.py &&
      ./manage.py migrate --noinput &&
      ./manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 --access-log - --proxy-headers config.asgi:application
      "
    volumes:
      - ./:/code
    expose:
      - 8000
    depends_on:
      - celeryworker
      - redis
    env_file:
      - .envs/.staging
      - .envs/.staging.db
      - .envs/.staging.web

  nginx-proxy:
    build: compose/nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .envs/.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

  celeryworker:
    <<: *web
    image: umbrella_staging_celeryworker
    container_name: umbrella_staging_celeryworker
    depends_on:
      - redis
    ports: [ ]
    command: celery -A config.celery_app worker -l INFO -E
    env_file:
      - .envs/.staging
      - .envs/.staging.db

  flower:
    <<: *web
    image: umbrella_staging_flower
    container_name: umbrella_staging_flower
    ports:
      - "5555:5555"
    command: ./compose/start-flower
    env_file:
      - .envs/.staging
      - .envs/.staging.db

  redis:
    image: redis:6
    container_name: umbrella_staging_redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
  certs:
  html:
  vhost:
  acme:
