version: '3.7'

services:
  keycloak:
    container_name: keycloak_app
    image: jboss/keycloak
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - "/home/ubuntu/ssl_2021/:/etc/x509/https"   # map certificates to container
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 3pbE7MYDwzNwDaxw
      KEYCLOAK_HTTPS_PORT: 8443
