# Generated by Django 4.0.1 on 2022-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realm',
            field=models.CharField(default='no_realm', max_length=255, verbose_name='User realm'),
        ),
    ]
