# Generated by Django 4.0.2 on 2022-04-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_realm'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_groups', to='auth.group')),
            ],
        ),
    ]
