# Generated by Django 4.0.1 on 2022-03-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import umbrella.tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_rename_activeflag_lease_active_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=128)),
                ('bl_type', models.CharField(max_length=128)),
                ('link_to_text', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=128)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=32)),
                ('when', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=32)),
                ('repeats', models.CharField(choices=[('NEVER', 'Not Never'), ('EVERYDAY', 'Everyday'), ('EVERY_WEEK', 'Every week'), ('EVERY_MONTH', 'Every month')], default='EVERYDAY', max_length=32)),
                ('until', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(related_name='executors', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.lease')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(umbrella.tasks.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
