# Generated by Django 4.0.1 on 2022-03-17 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('OVERDUE', 'Overdue'), ('DUE_TODAY', 'Due Today'), ('DUE_IN_A_WEEK', 'Due in a Week'), ('DUE_IN_A_MONTH', 'Due in a Month'), ('NOT_DUE_SOON', 'Not Due Soon')], default='DONE', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='executors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeats',
            field=models.CharField(choices=[('NEVER', 'Not Never'), ('EVERYDAY', 'Everyday'), ('EVERY_WEEK', 'Every week'), ('EVERY_MONTH', 'Every month')], default='NEVER', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checklist', to='tasks.task'),
        ),
    ]
