# Generated by Django 4.0.1 on 2022-03-23 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='when',
            new_name='reminder_before_or_after',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='number',
            new_name='reminder_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='period',
            new_name='reminder_period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
