# Generated by Django 4.0.1 on 2022-03-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_when_task_reminder_before_or_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='bl_type',
            new_name='business_intelligence_type',
        ),
    ]
