# Generated by Django 4.0.2 on 2022-04-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_parent_tags'),
        ('tasks', '0002_alter_task_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='contracts.contract'),
        ),
    ]
