# Generated by Django 4.0.1 on 2022-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_bl_type_task_business_intelligence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='business_intelligence_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='clause_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='link_to_text',
            field=models.TextField(),
        ),
    ]
