# Generated by Django 4.0.1 on 2022-03-22 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_comment_subtask_remove_taskcomment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
