# Generated by Django 3.2.10 on 2021-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('pdf', models.BinaryField(blank=True)),
                ('txt', models.TextField(null=True)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(max_length=128)),
                ('contract_type', models.CharField(max_length=32)),
                ('textract', models.JSONField(blank=True, null=True)),
                ('analyticsdata', models.JSONField(blank=True, null=True)),
                ('modified_file_name', models.CharField(max_length=256)),
                ('analytics2', models.JSONField(blank=True, null=True)),
                ('doc_type', models.CharField(max_length=258)),
            ],
            options={
                'db_table': 'lease',
            },
        ),
    ]
