# Generated by Django 3.2.10 on 2021-12-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0002_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='activeflag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='modifiedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='pdf_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='contract_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='createdby',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='doc_type',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='file_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lease',
            name='modified_file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='modifiedby',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
