# Generated by Django 3.2.10 on 2021-12-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0003_auto_20211213_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'managed': True},
        ),
    ]
