# Generated by Django 4.0.1 on 2022-04-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('pdf', models.BinaryField(blank=True, null=True)),
                ('txt', models.TextField(blank=True, null=True)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=128, null=True)),
                ('active_flag', models.BooleanField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=32, null=True)),
                ('textract', models.JSONField(blank=True, null=True)),
                ('analytics_data', models.JSONField(blank=True, null=True)),
                ('file_hash', models.TextField(unique=True)),
                ('file_size', models.BigIntegerField()),
                ('modified_file_name', models.CharField(max_length=256, unique=True)),
                ('analytics_two', models.JSONField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=258, null=True)),
                ('textract_done', models.BooleanField(default=False)),
                ('analytics_done', models.BooleanField(default=False)),
                ('normalization_done', models.BooleanField(default=False)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='leases', to='auth.Group')),
            ],
            options={
                'db_table': 'lease',
            },
        ),
    ]
