# Generated by Django 4.0.1 on 2022-03-15 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lease',
            name='file_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lease',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='modified_file_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
