# Generated by Django 4.0.2 on 2022-04-10 11:41

import uuid

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512)),
                ('pdf', models.BinaryField(blank=True, null=True)),
                ('txt', models.TextField(blank=True, null=True)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=128, null=True)),
                ('active_flag', models.BooleanField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=32, null=True)),
                ('textract', models.JSONField(blank=True, null=True)),
                ('analytics_data', models.JSONField(blank=True, null=True)),
                ('file_hash', models.TextField(unique=True)),
                ('file_size', models.BigIntegerField()),
                ('modified_file_name', models.CharField(max_length=256, unique=True)),
                ('analytics_two', models.JSONField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=258, null=True)),
                ('textract_done', models.BooleanField(default=False)),
                ('analytics_done', models.BooleanField(default=False)),
                ('normalization_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lease',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lease',
        ),
    ]
