# Generated by Django 4.0.1 on 2022-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contracts', '0003_rename_activeflag_lease_active_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='leases', to='auth.Group'),
        ),
    ]
