# Generated by Django 4.0.1 on 2022-04-02 01:05

import uuid

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0004_lease_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
