# Generated by Django 4.0.2 on 2022-04-22 18:29

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contracts', '0006_contract_parent_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('tag_type', models.CharField(choices=[('nt', 'Nature'), ('tp', 'Type'), ('gr', 'Groups'), ('oth', 'Others')], max_length=128)),
                ('contracts', models.ManyToManyField(blank=True, related_name='tags', to='contracts.Contract')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
