# Generated by Django 4.0.4 on 2022-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_parent_tag_contract_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='extracted_json_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
