# Generated by Django 4.0.2 on 2022-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_tag_delete_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_type',
            new_name='type',
        ),
    ]
