# Generated by Django 4.0.4 on 2022-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_contract_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='extracted_json_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
