# Generated by Django 4.0.2 on 2022-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_rename_tag_type_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='contracts',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='contracts.Contract'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('type', 'Type'), ('groups', 'Groups'), ('others', 'Others')], max_length=128),
        ),
    ]
