# Generated by Django 4.0.2 on 2022-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_tag_contracts_alter_tag_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='contracts',
        ),
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='contracts', to='contracts.Tag'),
        ),
    ]
