name: Deploy

on:
  push:
    branches: [ production, staging ]

jobs:
  test:
    uses: ./github/workflows/test_workflow@develop
  deploy:
    uses: ./github/workflows/deploy_workflow@develop
    needs: test
