name: Deploy

on:
  push:
    branches: [ production, staging ]

jobs:
  test:
    uses: ./.github/workflows/test_workflow.yaml
  deploy:
    uses: ./.github/workflows/deploy_workflow.yaml
    needs: test
