name: Test

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build compose containers
      run: |
        cp .envs/.env.local.example .envs/.env.local
        docker-compose -f local.yml up -d web postgres
    - name: Run pytest
      run: docker-compose -f local.yml exec web pytest
    - name: Run flake8
      run: docker-compose -f local.yml exec web flake8
