name: Test

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pytest using docker-compose
      run: |
        cp .envs/.env.local.example .envs/.env.local
        docker-compose -f local.yml run web pytest
